### PR TITLE
add hadoop conf dir to classpath

### LINKED ISSUE #101: hadoop config path is not in classpath by default

### PR DESCRIPTION
**Pull request by sandflee**
fixes #101

### CODE REVIEW

**Comment by Xuanwo** [comment]
This PR LGTM to me, just need to address a warning:

```shell
Error:    --> src/client.rs:376:31
    |
376 |         for d in fs::read_dir(&path)? {
    |                               ^^^^^ help: change this to: `path`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `-D clippy::needless-borrow` implied by `-D warnings`
```

**Comment by sandflee** [comment]
> This PR LGTM to me, just need to address a warning:
> 
> ```shell
> Error:    --> src/client.rs:376:31
>     |
> 376 |         for d in fs::read_dir(&path)? {
>     |                               ^^^^^ help: change this to: `path`
>     |
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
>     = note: `-D clippy::needless-borrow` implied by `-D warnings`
> ```

updated

**Comment by sandflee** [comment]
seems could't be simply fixed, will see it latter

**Comment by Xuanwo** [comment]
> seems could't be simply fixed, will see it latter

I triggered a test on `main` branch, can't reproduce this test failure.

**Comment by Xuanwo** [comment]
Let's close this PR for now.

**Pull request closed without merging**
